# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('unit1', models.CharField(max_length=20)),
                ('unit2', models.CharField(max_length=20)),
            ],
        ),
    ]
