# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='value',
            field=models.FloatField(),
        ),
    ]
